# https://github.com/kubernetes/kubernetes/releases
# https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
# STABLE=https://dl.k8s.io/release/stable.txt
# - https://dl.k8s.io/release/v1.36.2/bin/linux/amd64/kubectl
# - https://dl.k8s.io/release/v1.36.2/bin/linux/amd64/kubectl.sha256

# https://github.com/GoogleContainerTools/skaffold/releases
# - https://storage.googleapis.com/skaffold/releases/v1.20.0/skaffold-linux-amd64
# - https://github.com/GoogleContainerTools/skaffold/releases/download/v1.20.0/skaffold-linux-amd64.sha256

runs:
  using: composite
  steps:
    - id: cache-bin
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: bin
        key: ${{ runner.os }}-bin-v2
    - if: steps.cache-bin.outputs.cache-hit != 'true'
      name: Download tools
      shell: bash
      run: |
        mkdir bin
        curl -Lo bin/skaffold https://storage.googleapis.com/skaffold/releases/v1.20.0/skaffold-linux-amd64
        echo "725b5b5b9456cb1abc26c8a7528906e27c30980cda79249d780618c3834a7aa3  bin/skaffold" | sha256sum -c -
        curl -Lo bin/kubectl https://dl.k8s.io/release/v1.36.2/bin/linux/amd64/kubectl
        echo "1e9045ec32bea85da43de85f0065358529ea7c7a152eca78154fba5b58c27d82  bin/kubectl" | sha256sum -c -
        chmod +x bin/skaffold bin/kubectl
    - name: Add tools to PATH
      shell: bash
      run: echo "$PWD/bin" >> $GITHUB_PATH
