os: linux
dist: focal
language: python
env:
  - DEBUG=1 SECRET_KEY='x' ALLOWED_HOSTS='*'
python: "3.9"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-oauth.txt
  - pip install -r requirements-dev.txt
script:
  - py.test -vvv --cov . --doctest-modules
after_success:
  - bash <(curl -s https://codecov.io/bash)
