# Stage 0
FROM node:20-alpine
WORKDIR /usr/src/app/kirppu

COPY kirppu/package.json kirppu/package-lock.json ./
RUN --mount=type=cache,target=/root/.npm \
    npm ci

COPY kirppu ./
RUN mkdir /usr/src/build && npm run gulp -- --dest /usr/src/build --type production


# Stage 1
FROM python:3.13
WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get -y install gettext && \
    mkdir -p /usr/src/app/kirppu && \
    groupadd -r kirppu && \
    useradd -r -g kirppu kirppu && \
    rm -rf /var/lib/apt/lists

COPY constraints.txt requirements-dev.txt requirements-production.txt /usr/src/app/
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements-dev.txt -r requirements-production.txt

COPY . ./
COPY --from=0 /usr/src/build /usr/src/app/kirppu/static/kirppu

RUN env DEBUG=1 python manage.py collectstatic --noinput && \
    env DEBUG=1 python manage.py compilemessages && \
    python -m compileall -q .

USER kirppu
EXPOSE 8000
ENTRYPOINT ["/usr/src/app/scripts/docker-entrypoint.sh"]
CMD ["python", "manage.py", "docker_start"]
