djangoapp_secret_managed: false
djangoapp_admins:
  - Jyrki Launonen <codez@tracon.fi>

ingress_public_hostname: kirppu.tracon.fi
backup_ingress_public_hostnames:
  - vara.kirppu.tracon.fi

postgres_managed: false
postgres_ssl: true

setup_should_run: true

smtp_server: sr1.pahaip.fi
smtp_default_from_email: root@tracon.fi

ingress_letsencrypt_enabled: true
ingress_letsencrypt_cluster_issuer: letsencrypt-prod
