name: cicd

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - development
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
      COMPOSE_DOCKER_CLI_BUILD: "1"
    steps:
      - uses: &checkout-action actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: &buildx-action docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - run: docker compose -f docker-compose.test.yml up --exit-code-from test

  build:
    runs-on: ubuntu-latest
    env:
      SKAFFOLD_DEFAULT_REPO: ghcr.io/con2
    steps:
      - uses: *checkout-action
      - uses: &python-action actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11'
      - uses: ./.github/cache-tools
      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        if: ${{ github.event_name == 'push' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: *buildx-action
      - id: build
        run: |
          python3 -m pip install emskaffolden

          # Do not push to registry on pull request events
          if [ "${{ github.event_name }}" = pull_request ]; then
            EMSKAFFOLDEN_ENV=pull_request
          else
            EMSKAFFOLDEN_ENV=default
          fi

          emskaffolden -E "$EMSKAFFOLDEN_ENV" -- build --file-output build.json
          echo "build_json=$(base64 -w 0 < build.json)" >> "$GITHUB_OUTPUT"
    outputs:
      build_json: ${{ steps.build.outputs.build_json }}

  # TODO DRY
  deploy_staging:
    runs-on: qb-arc-runners
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/development' }}
    steps:
      - uses: *checkout-action
      - uses: *python-action
        with:
          python-version: '3.11'
      - uses: ./.github/cache-tools
      - run: |
          python3 -m pip install emskaffolden
          base64 -d <<< "${{ needs.build.outputs.build_json }}" > build.json
          emskaffolden -E staging -- deploy -n kirppu-staging -a build.json

  deploy_production:
    runs-on: qb-arc-runners
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - uses: *checkout-action
      - uses: *python-action
        with:
          python-version: '3.11'
      - uses: ./.github/cache-tools
      - run: |
          python3 -m pip install emskaffolden
          base64 -d <<< "${{ needs.build.outputs.build_json }}" > build.json
          emskaffolden -E production -- deploy -n kirppu -a build.json
