name: Test

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: constraints.txt requirements-dev.txt
      - run: pip install -r requirements-dev.txt
      - run: py.test -vvv --cov . --doctest-modules
        env:
          DEBUG: "1"
          SECRET_KEY: "x"
          ALLOWED_HOSTS: "*"
      - uses: codecov/codecov-action@v3
